// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddManySongToAlbum(ctx context.Context, arg AddManySongToAlbumParams) error
	AddSongToAlbum(ctx context.Context, arg AddSongToAlbumParams) error
	AddSongToFavorite(ctx context.Context, arg AddSongToFavoriteParams) error
	AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error
	AdminDeletePlaylist(ctx context.Context, playlistID int32) error
	AdminGetSongs(ctx context.Context) ([]AdminGetSongsRow, error)
	ChangePassword(ctx context.Context, arg ChangePasswordParams) error
	CheckEmailExists(ctx context.Context, email string) (int32, error)
	CheckFavorite(ctx context.Context, arg CheckFavoriteParams) (int32, error)
	CheckFollow(ctx context.Context, arg CheckFollowParams) (ArtistFollow, error)
	CheckOwnerPlaylist(ctx context.Context, arg CheckOwnerPlaylistParams) (CheckOwnerPlaylistRow, error)
	CheckSongInAlbum(ctx context.Context, arg CheckSongInAlbumParams) (int64, error)
	CheckSongInPlaylist(ctx context.Context, arg CheckSongInPlaylistParams) (int64, error)
	CountAlbums(ctx context.Context) (int64, error)
	CountAlbumsByArtistID(ctx context.Context, artistID int32) (int64, error)
	CountListArtists(ctx context.Context, nameSearch pgtype.Text) (int64, error)
	CountSearchAlbums(ctx context.Context, search pgtype.Text) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error)
	CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	CreateUserPlaylist(ctx context.Context, arg CreateUserPlaylistParams) (Playlist, error)
	DeleteAlbum(ctx context.Context, id int32) error
	DeleteArtist(ctx context.Context, id int32) error
	DeleteCategories(ctx context.Context, id int32) error
	DeleteComment(ctx context.Context, id int32) error
	DeleteManyArtist(ctx context.Context, ids []int32) error
	DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSong(ctx context.Context, id int32) error
	Follow(ctx context.Context, arg FollowParams) error
	GetAccount(ctx context.Context, email string) (GetAccountRow, error)
	GetAlbumByArtistID(ctx context.Context, artistID int32) ([]Album, error)
	GetAlbumByID(ctx context.Context, id int32) (Album, error)
	GetAlbumInfoFromSongID(ctx context.Context, songID int32) (GetAlbumInfoFromSongIDRow, error)
	GetAlbumSong(ctx context.Context, albumID int32) ([]GetAlbumSongRow, error)
	GetAlbums(ctx context.Context, arg GetAlbumsParams) ([]GetAlbumsRow, error)
	GetAllAlbum(ctx context.Context) ([]GetAllAlbumRow, error)
	GetAllArtistForAdmin(ctx context.Context) ([]Artist, error)
	GetAllPlaylist(ctx context.Context) ([]Playlist, error)
	GetArtistById(ctx context.Context, id int32) (GetArtistByIdRow, error)
	GetCommentById(ctx context.Context, id int32) (Comment, error)
	GetFavoriteSongs(ctx context.Context, accountID int32) ([]GetFavoriteSongsRow, error)
	GetFollowedArtist(ctx context.Context, accountID int32) ([]GetFollowedArtistRow, error)
	GetListArtists(ctx context.Context, nameSearch pgtype.Text) ([]Artist, error)
	GetNewAlbum(ctx context.Context) ([]GetNewAlbumRow, error)
	GetNewPlaylist(ctx context.Context) ([]Playlist, error)
	GetNewSongs(ctx context.Context) ([]GetNewSongsRow, error)
	GetPlaylistByArtist(ctx context.Context, artistID int32) ([]Playlist, error)
	GetPlaylistByCategories(ctx context.Context, categoryID int32) ([]Playlist, error)
	GetPlaylistById(ctx context.Context, id int32) (Playlist, error)
	GetPlaylistByUserId(ctx context.Context, accountID int32) ([]GetPlaylistByUserIdRow, error)
	GetPlaylistofUser(ctx context.Context, accountID pgtype.Int4) ([]Playlist, error)
	GetRandomSong(ctx context.Context) ([]GetRandomSongRow, error)
	GetRecommentArtist(ctx context.Context) ([]Artist, error)
	GetSecretKey(ctx context.Context, email string) (pgtype.Text, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByRfToken(ctx context.Context, refreshToken string) (Session, error)
	GetSongByAlbum(ctx context.Context, arg GetSongByAlbumParams) ([]GetSongByAlbumRow, error)
	GetSongByID(ctx context.Context, id int32) (GetSongByIDRow, error)
	GetSongById(ctx context.Context, id int32) (GetSongByIdRow, error)
	GetSongCategories(ctx context.Context) ([]Category, error)
	GetSongComment(ctx context.Context, songID int32) ([]GetSongCommentRow, error)
	GetSongInCategory(ctx context.Context, arg GetSongInCategoryParams) ([]GetSongInCategoryRow, error)
	GetSongInPlaylist(ctx context.Context, playlistID int32) ([]GetSongInPlaylistRow, error)
	GetSongNotInAlbum(ctx context.Context, arg GetSongNotInAlbumParams) ([]GetSongNotInAlbumRow, error)
	GetSongNotInPlaylist(ctx context.Context, arg GetSongNotInPlaylistParams) ([]GetSongNotInPlaylistRow, error)
	GetSongOfArtist(ctx context.Context, id int32) ([]GetSongOfArtistRow, error)
	GetSongOfPlaylist(ctx context.Context, playlistID int32) ([]GetSongOfPlaylistRow, error)
	GetSongViewStatistics(ctx context.Context, arg GetSongViewStatisticsParams) ([]GetSongViewStatisticsRow, error)
	GetSongs(ctx context.Context, arg GetSongsParams) ([]GetSongsRow, error)
	GetUserInfo(ctx context.Context, email string) (GetUserInfoRow, error)
	PlaySong(ctx context.Context, arg PlaySongParams) error
	RemoveSongFromAlbum(ctx context.Context, arg RemoveSongFromAlbumParams) error
	RemoveSongFromFavorite(ctx context.Context, arg RemoveSongFromFavoriteParams) error
	RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error
	SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]SearchAlbumsRow, error)
	SearchArtist(ctx context.Context, search string) ([]SearchArtistRow, error)
	SearchPlaylist(ctx context.Context, search string) ([]Playlist, error)
	SearchSong(ctx context.Context, arg SearchSongParams) ([]SearchSongRow, error)
	Statistics(ctx context.Context) (StatisticsRow, error)
	UnFollow(ctx context.Context, arg UnFollowParams) error
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error)
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error)
	UpdateCategories(ctx context.Context, arg UpdateCategoriesParams) (Category, error)
	UpdateName(ctx context.Context, arg UpdateNameParams) error
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
	UpdateSessionID(ctx context.Context, arg UpdateSessionIDParams) error
	UpdateSong(ctx context.Context, arg UpdateSongParams) error
	VerifyAccount(ctx context.Context, email string) (Account, error)
}

var _ Querier = (*Queries)(nil)
